export const rxNormSampleResponseData = {
  allRelatedGroup: {
    rxcui: "",
    conceptGroup: [
      {
        tty: "BN",
        conceptProperties: [
          {
            rxcui: "1101916",
            name: "Counteract IB",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1300262",
            name: "Proprinal",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "153010",
            name: "Advil",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "202488",
            name: "Motrin",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "217324",
            name: "Genpril",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "643099",
            name: "Wal-Profen",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "850404",
            name: "Ibuprohm",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "900431",
            name: "Addaprin",
            synonym: "",
            tty: "BN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      { tty: "BPCK" },
      {
        tty: "DF",
        conceptProperties: [
          {
            rxcui: "317541",
            name: "Oral Tablet",
            synonym: "",
            tty: "DF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      {
        tty: "DFG",
        conceptProperties: [
          {
            rxcui: "1151131",
            name: "Oral Product",
            synonym: "",
            tty: "DFG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1151133",
            name: "Pill",
            synonym: "",
            tty: "DFG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      { tty: "GPCK" },
      {
        tty: "IN",
        conceptProperties: [
          {
            rxcui: "5640",
            name: "ibuprofen",
            synonym: "",
            tty: "IN",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      { tty: "MIN" },
      { tty: "PIN" },
      {
        tty: "SBD",
        conceptProperties: [
          {
            rxcui: "1101919",
            name: "ibuprofen 200 MG Oral Tablet [Counteract IB]",
            synonym: "Counteract IB 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1300267",
            name: "ibuprofen 200 MG Oral Tablet [Proprinal]",
            synonym: "Proprinal 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "153008",
            name: "ibuprofen 200 MG Oral Tablet [Advil]",
            synonym: "Advil 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "201126",
            name: "ibuprofen 200 MG Oral Tablet [Motrin]",
            synonym: "Motrin 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "206886",
            name: "ibuprofen 200 MG Oral Tablet [Genpril]",
            synonym: "Genpril 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "643102",
            name: "ibuprofen 200 MG Oral Tablet [Wal-Profen]",
            synonym: "Wal-Profen 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "850424",
            name: "ibuprofen 200 MG Oral Tablet [Ibuprohm]",
            synonym: "Ibuprohm 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "900434",
            name: "ibuprofen 200 MG Oral Tablet [Addaprin]",
            synonym: "Addaprin 200 MG Oral Tablet",
            tty: "SBD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      {
        tty: "SBDC",
        conceptProperties: [
          {
            rxcui: "1101917",
            name: "ibuprofen 200 MG [Counteract IB]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1300263",
            name: "ibuprofen 200 MG [Proprinal]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "565143",
            name: "ibuprofen 200 MG [Advil]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "565689",
            name: "ibuprofen 200 MG [Motrin]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "567688",
            name: "ibuprofen 200 MG [Genpril]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "643100",
            name: "ibuprofen 200 MG [Wal-Profen]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "850422",
            name: "ibuprofen 200 MG [Ibuprohm]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "900432",
            name: "ibuprofen 200 MG [Addaprin]",
            synonym: "",
            tty: "SBDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      {
        tty: "SBDF",
        conceptProperties: [
          {
            rxcui: "1101918",
            name: "ibuprofen Oral Tablet [Counteract IB]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1300264",
            name: "ibuprofen Oral Tablet [Proprinal]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "368840",
            name: "ibuprofen Oral Tablet [Genpril]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "643101",
            name: "ibuprofen Oral Tablet [Wal-Profen]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "850423",
            name: "ibuprofen Oral Tablet [Ibuprohm]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "900433",
            name: "ibuprofen Oral Tablet [Addaprin]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "91703",
            name: "ibuprofen Oral Tablet [Advil]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "93358",
            name: "ibuprofen Oral Tablet [Motrin]",
            synonym: "",
            tty: "SBDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      { tty: "SBDFP" },
      {
        tty: "SBDG",
        conceptProperties: [
          {
            rxcui: "1166591",
            name: "Ibuprohm Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1166592",
            name: "Ibuprohm Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1169834",
            name: "Genpril Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1169835",
            name: "Genpril Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1170617",
            name: "Addaprin Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1170618",
            name: "Addaprin Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1171346",
            name: "Advil Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1171662",
            name: "Counteract IB Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1171663",
            name: "Counteract IB Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1172038",
            name: "Advil Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1182818",
            name: "Motrin Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1182821",
            name: "Motrin Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1187794",
            name: "Wal-Profen Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1187795",
            name: "Wal-Profen Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1300265",
            name: "Proprinal Oral Product",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1300266",
            name: "Proprinal Pill",
            synonym: "",
            tty: "SBDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      {
        tty: "SCD",
        conceptProperties: [
          {
            rxcui: "310965",
            name: "ibuprofen 200 MG Oral Tablet",
            synonym:
              "ibuprofen 200 MG (as ibuprofen sodium 256 MG) Oral Tablet",
            tty: "SCD",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      {
        tty: "SCDC",
        conceptProperties: [
          {
            rxcui: "316074",
            name: "ibuprofen 200 MG",
            synonym: "",
            tty: "SCDC",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      {
        tty: "SCDF",
        conceptProperties: [
          {
            rxcui: "370674",
            name: "ibuprofen Oral Tablet",
            synonym: "",
            tty: "SCDF",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      { tty: "SCDFP" },
      {
        tty: "SCDG",
        conceptProperties: [
          {
            rxcui: "1156277",
            name: "ibuprofen Oral Product",
            synonym: "",
            tty: "SCDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
          {
            rxcui: "1156278",
            name: "ibuprofen Pill",
            synonym: "",
            tty: "SCDG",
            language: "ENG",
            suppress: "N",
            umlscui: "",
          },
        ],
      },
      { tty: "SCDGP" },
    ],
  },
};
